package org.example;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.Arrays;
import java.util.List;
import io.substrait.isthmus.SqlToSubstrait;
import io.substrait.proto.Plan;
import com.google.protobuf.util.JsonFormat;
import org.slf4j.LoggerFactory;


public class DDLExample{
    public static void enableTraceLogging() {

    }

    public static void main(String[] args){
        //enableTraceLogging();

        try {
            SqlToSubstrait converter = new SqlToSubstrait();

            List<String> tables = Arrays.asList("CREATE TABLE EMPLOYEE (\r\n" + //
                    "    id INTEGER ,\r\n" + //
                    "    NAME VARCHAR(20) NOT NULL,\r\n" + //
                    "    SALARY INTEGER NOT NULL);\r\n"
                    ,
                    "CREATE TABLE clickstream(\r\n" + //
                            "    userId INTEGER ,\r\n" + //
                            "    event_time timestamp,\r\n" + //
                            "    projid INTEGER);\r\n"

            );

            String sql = "SELECT * FROM clickstream;";

            Plan plan = converter.execute(sql, tables);
            String json=JsonFormat.printer()
                    .includingDefaultValueFields()
                    .preservingProtoFieldNames()
                    .print(plan);

            System.out.println("Generated Substrait plan:");
            System.out.println(json);

        } catch(Exception e){
            e.printStackTrace();
        }
    }
}
