/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 */


plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

group = "calcite.server"
version = "1.0.0"

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    //Calcite 
    implementation("org.apache.calcite:calcite-core:1.37.0")
    implementation("org.apache.calcite:calcite-server:1.32.0")


    //Substrait
    implementation("io.substrait:isthmus:0.56.0")

    //Jackson
    implementation("com.fasterxml.jackson.core:jackson-databind:2.19.0")

    //Protobuf    
    implementation("com.google.protobuf:protobuf-java-util:4.30.2")
    implementation("com.google.protobuf:protobuf-java:4.30.2")



    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre") 
}


application {
    // Define the main class for the application.
    mainClass.set("calcite.server.CalciteServer")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar> {
    archiveBaseName.set("calcite.server")
    archiveClassifier.set("all")
    archiveVersion.set(version.toString())
}