/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calcite.server;


import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.util.concurrent.Executors;
import java.util.concurrent.ConcurrentHashMap;



public class CalciteServer {
    private static final int PORT = 8080;

    // Global hashmap to store topic -> CREATE TABLE statement mappings
    private final ConcurrentHashMap<String, String> tableDefinitions = new ConcurrentHashMap<>();
    public static void main(String[] args) {
        CalciteServer service = new CalciteServer();
        try{
            service.startServer();
        }catch(Exception e){
            System.err.println(e.toString());
        }
    }

    public void startServer() throws IOException {
        HttpServer server = HttpServer.create(new InetSocketAddress(PORT), 0);

        // Set up the endpoints - create contexts with proper routing logic
        server.createContext("/create", new CreateHandler(tableDefinitions));
        server.createContext("/alter", new AlterHandler(tableDefinitions));
        server.createContext("/getSubstrait", new GetSubstraitPlanHandler(tableDefinitions));
        server.createContext("/delete", new DeleteHandler(tableDefinitions));

        server.setExecutor(Executors.newCachedThreadPool());
        server.start();
        System.out.println("Server started on port " + PORT);
    }  

}
