/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calcite.server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        CalciteServer classUnderTest = new CalciteServer();
    }
}
